;
; File generated by cc65 v 2.19 - Git 96e8e89
;
	.fopt		compiler,"cc65 v 2.19 - Git 96e8e89"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "fullbg.c", 10165, 1748043012
	.dbg		file, "libs/neslib.h", 8998, 1746954991
	.dbg		file, "libs/nesdoug.h", 6588, 1746973112
	.dbg		file, "graphics/AllOk.h", 2000, 1746907457
	.dbg		file, "graphics/Disaster.h", 5289, 1746907446
	.dbg		file, "graphics/Desert.h", 1484, 1746907450
	.dbg		file, "graphics/LightInDesert.h", 5294, 1747044321
	.dbg		file, "graphics/The3Heroes.h", 5575, 1747049602
	.dbg		file, "graphics/SealAngelHeaven.h", 1575, 1746907433
	.dbg		file, "graphics/Clear.h", 464, 1746917832
	.dbg		file, "graphics/NameTableLoader.h", 297, 1746958024
	.dbg		file, "vrc6/vrc6_code.h", 2956, 1676486867
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_bright
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_bank_spr
	.import		_set_vram_update
	.import		_vram_adr
	.import		_vram_put
	.import		_vram_fill
	.import		_vram_write
	.import		_vram_unrle
	.import		_delay
	.import		_pal_fade_to
	.export		_allOk
	.export		_disaster
	.export		_desert
	.export		_lightInDesert
	.export		_the3Heroes
	.export		_the3Heroes_attr
	.export		_sealAngelHeaven
	.export		_clear
	.export		_nameTableLoader
	.export		_bankLevel
	.export		_bankBuffer
	.import		_set_chr_mode_0
	.import		_set_chr_mode_1
	.import		_set_chr_mode_2
	.import		_set_chr_mode_3
	.import		_disable_irq
	.import		_set_irq_ptr
	.import		_is_irq_done
	.export		_i
	.export		_fi
	.export		_fj
	.export		_fk
	.export		_fi16
	.export		_black
	.export		_delay_time
	.export		_palette
	.export		_mensaje1
	.export		_mensaje2
	.export		_mensaje3
	.export		_mensaje4
	.export		_mensaje5
	.export		_mensaje6
	.export		_mensaje7
	.export		_mensaje8
	.export		_mensaje9
	.export		_mensaje10
	.export		_mensaje11
	.export		_mensaje12
	.export		_mensaje13
	.export		_mensaje14
	.export		_mensaje15
	.export		_mensaje16
	.export		_mensaje17
	.export		_mandador
	.export		_irq_buffer
	.export		_wram_array
	.export		_custom_fade_in
	.export		_load_nametable_a_during_vblank
	.export		_fade_in
	.export		_fade_out
	.export		_fade_out_white
	.export		_fade_in_white
	.export		_map_to
	.export		_fix_text_color
	.export		_print
	.export		_clear_4_lines
	.export		_change_std_scanline
	.export		_main

.segment	"DATA"

_clear:
	.byte	$62
	.byte	$00
	.byte	$40
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
_nameTableLoader:
	.byte	$60
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$FF
_black:
	.byte	$FF
_delay_time:
	.byte	$03
_palette:
	.byte	$0F
	.byte	$07
	.byte	$17
	.byte	$27
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$07
	.byte	$17
	.byte	$30
_mandador:
	.byte	$62
	.byte	$89
	.byte	$01
	.byte	$41
	.byte	$FF

.segment	"RODATA"

_allOk:
	.byte	$A0
	.byte	$00
	.byte	$A0
	.byte	$83
	.byte	$01
	.byte	$A0
	.byte	$0C
	.byte	$45
	.byte	$46
	.byte	$A0
	.byte	$09
	.byte	$00
	.byte	$A0
	.byte	$06
	.byte	$02
	.byte	$03
	.byte	$A0
	.byte	$07
	.byte	$04
	.byte	$05
	.byte	$03
	.byte	$04
	.byte	$03
	.byte	$2F
	.byte	$16
	.byte	$A0
	.byte	$09
	.byte	$47
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$A0
	.byte	$07
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$03
	.byte	$48
	.byte	$16
	.byte	$A0
	.byte	$06
	.byte	$49
	.byte	$4A
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$03
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$13
	.byte	$14
	.byte	$29
	.byte	$4C
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$4D
	.byte	$4E
	.byte	$16
	.byte	$4F
	.byte	$50
	.byte	$51
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$15
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$17
	.byte	$03
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$2F
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$16
	.byte	$56
	.byte	$57
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$1D
	.byte	$16
	.byte	$A0
	.byte	$03
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$21
	.byte	$03
	.byte	$03
	.byte	$48
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$58
	.byte	$16
	.byte	$16
	.byte	$59
	.byte	$5A
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$22
	.byte	$23
	.byte	$16
	.byte	$24
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$28
	.byte	$03
	.byte	$03
	.byte	$29
	.byte	$4C
	.byte	$16
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$5E
	.byte	$5F
	.byte	$16
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$03
	.byte	$2A
	.byte	$16
	.byte	$16
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$2E
	.byte	$03
	.byte	$03
	.byte	$2F
	.byte	$16
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$30
	.byte	$31
	.byte	$16
	.byte	$16
	.byte	$32
	.byte	$33
	.byte	$34
	.byte	$35
	.byte	$03
	.byte	$03
	.byte	$36
	.byte	$16
	.byte	$6B
	.byte	$6C
	.byte	$16
	.byte	$6D
	.byte	$6E
	.byte	$6F
	.byte	$70
	.byte	$71
	.byte	$72
	.byte	$73
	.byte	$74
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$37
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$38
	.byte	$03
	.byte	$39
	.byte	$03
	.byte	$03
	.byte	$3A
	.byte	$3B
	.byte	$16
	.byte	$75
	.byte	$16
	.byte	$76
	.byte	$77
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$3C
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$3D
	.byte	$03
	.byte	$39
	.byte	$03
	.byte	$03
	.byte	$3E
	.byte	$16
	.byte	$A0
	.byte	$03
	.byte	$7B
	.byte	$16
	.byte	$A0
	.byte	$03
	.byte	$7C
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$3F
	.byte	$16
	.byte	$16
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$39
	.byte	$03
	.byte	$03
	.byte	$44
	.byte	$16
	.byte	$A0
	.byte	$02
	.byte	$52
	.byte	$7D
	.byte	$16
	.byte	$7E
	.byte	$7F
	.byte	$16
	.byte	$80
	.byte	$55
	.byte	$16
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$81
	.byte	$82
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$03
	.byte	$39
	.byte	$03
	.byte	$3A
	.byte	$3B
	.byte	$16
	.byte	$16
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$03
	.byte	$3E
	.byte	$16
	.byte	$A0
	.byte	$03
	.byte	$9B
	.byte	$9C
	.byte	$16
	.byte	$A0
	.byte	$03
	.byte	$9D
	.byte	$9E
	.byte	$16
	.byte	$16
	.byte	$4B
	.byte	$00
	.byte	$A0
	.byte	$05
	.byte	$8D
	.byte	$8E
	.byte	$A0
	.byte	$08
	.byte	$8F
	.byte	$90
	.byte	$A0
	.byte	$0D
	.byte	$9F
	.byte	$00
	.byte	$A0
	.byte	$FE
	.byte	$00
	.byte	$A0
	.byte	$A2
	.byte	$00
	.byte	$A0
	.byte	$00
_disaster:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$09
	.byte	$10
	.byte	$11
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$16
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$1D
	.byte	$10
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$21
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$23
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$24
	.byte	$25
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$26
	.byte	$27
	.byte	$17
	.byte	$00
	.byte	$00
	.byte	$28
	.byte	$29
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$2A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$2B
	.byte	$00
	.byte	$00
	.byte	$2C
	.byte	$00
	.byte	$2D
	.byte	$2E
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$04
	.byte	$00
	.byte	$0E
	.byte	$2F
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$31
	.byte	$32
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$33
	.byte	$10
	.byte	$34
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$0E
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$36
	.byte	$00
	.byte	$37
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$38
	.byte	$39
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3A
	.byte	$3B
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$3C
	.byte	$3D
	.byte	$3E
	.byte	$3F
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$38
	.byte	$44
	.byte	$0B
	.byte	$00
	.byte	$45
	.byte	$46
	.byte	$00
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$0D
	.byte	$00
	.byte	$00
	.byte	$0E
	.byte	$4A
	.byte	$00
	.byte	$00
	.byte	$4B
	.byte	$0F
	.byte	$4C
	.byte	$00
	.byte	$44
	.byte	$4D
	.byte	$4D
	.byte	$4E
	.byte	$4F
	.byte	$50
	.byte	$51
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$00
	.byte	$5D
	.byte	$5E
	.byte	$5F
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$62
	.byte	$6C
	.byte	$6D
	.byte	$6E
	.byte	$6F
	.byte	$70
	.byte	$71
	.byte	$72
	.byte	$73
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$00
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$7E
	.byte	$7F
	.byte	$80
	.byte	$81
	.byte	$81
	.byte	$81
	.byte	$75
	.byte	$82
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$5E
	.byte	$62
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$8E
	.byte	$88
	.byte	$8F
	.byte	$74
	.byte	$90
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$91
	.byte	$8F
	.byte	$8F
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$8F
	.byte	$8F
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$75
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$8F
	.byte	$9F
	.byte	$8F
	.byte	$8F
	.byte	$A0
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$04
	.byte	$A5
	.byte	$A6
	.byte	$A7
	.byte	$A6
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$8F
	.byte	$AD
	.byte	$AE
	.byte	$AF
	.byte	$8F
	.byte	$74
	.byte	$B0
	.byte	$8F
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$5E
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$8A
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$18
	.byte	$BE
	.byte	$00
	.byte	$BF
	.byte	$C0
	.byte	$C1
	.byte	$C2
	.byte	$C3
	.byte	$C4
	.byte	$8F
	.byte	$C5
	.byte	$C6
	.byte	$C7
	.byte	$88
	.byte	$C8
	.byte	$88
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$74
	.byte	$8F
	.byte	$C9
	.byte	$CA
	.byte	$CB
	.byte	$CC
	.byte	$CD
	.byte	$CE
	.byte	$CF
	.byte	$D0
	.byte	$D1
	.byte	$D2
	.byte	$D3
	.byte	$6B
	.byte	$6B
	.byte	$D4
	.byte	$D5
	.byte	$D6
	.byte	$D7
	.byte	$D8
	.byte	$D9
	.byte	$DA
	.byte	$DB
	.byte	$DC
	.byte	$DD
	.byte	$75
	.byte	$DE
	.byte	$5E
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$DF
	.byte	$E0
	.byte	$E1
	.byte	$E2
	.byte	$E3
	.byte	$E4
	.byte	$0B
	.byte	$01
	.byte	$E5
	.byte	$E6
	.byte	$E7
	.byte	$E8
	.byte	$E9
	.byte	$EA
	.byte	$EB
	.byte	$EC
	.byte	$ED
	.byte	$EE
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$EF
	.byte	$8F
	.byte	$F0
	.byte	$F1
	.byte	$F2
	.byte	$F3
	.byte	$F4
	.byte	$F5
	.byte	$F6
	.byte	$40
	.byte	$00
	.byte	$0E
	.byte	$F7
	.byte	$F8
	.byte	$F9
	.byte	$FA
	.byte	$FB
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$8F
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FD
	.byte	$FD
	.byte	$FD
	.byte	$FE
	.byte	$FD
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FE
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FC
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_desert:
	.byte	$AC
	.byte	$00
	.byte	$AC
	.byte	$FE
	.byte	$00
	.byte	$AC
	.byte	$07
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$00
	.byte	$AC
	.byte	$11
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$AC
	.byte	$02
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$07
	.byte	$00
	.byte	$AC
	.byte	$02
	.byte	$16
	.byte	$17
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$12
	.byte	$AC
	.byte	$03
	.byte	$21
	.byte	$5E
	.byte	$5F
	.byte	$0F
	.byte	$0F
	.byte	$60
	.byte	$61
	.byte	$0F
	.byte	$3E
	.byte	$62
	.byte	$63
	.byte	$34
	.byte	$AC
	.byte	$02
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$0F
	.byte	$AC
	.byte	$05
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$12
	.byte	$28
	.byte	$29
	.byte	$12
	.byte	$AC
	.byte	$02
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6C
	.byte	$6D
	.byte	$0F
	.byte	$AC
	.byte	$06
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$1D
	.byte	$2E
	.byte	$2F
	.byte	$0F
	.byte	$AC
	.byte	$05
	.byte	$30
	.byte	$31
	.byte	$32
	.byte	$26
	.byte	$6E
	.byte	$6F
	.byte	$70
	.byte	$71
	.byte	$72
	.byte	$12
	.byte	$12
	.byte	$73
	.byte	$74
	.byte	$AC
	.byte	$02
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$0F
	.byte	$33
	.byte	$34
	.byte	$35
	.byte	$36
	.byte	$AC
	.byte	$02
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$2F
	.byte	$0F
	.byte	$AC
	.byte	$04
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$12
	.byte	$7E
	.byte	$7F
	.byte	$80
	.byte	$81
	.byte	$82
	.byte	$83
	.byte	$84
	.byte	$0F
	.byte	$AC
	.byte	$02
	.byte	$3C
	.byte	$3D
	.byte	$3E
	.byte	$3F
	.byte	$40
	.byte	$41
	.byte	$0F
	.byte	$42
	.byte	$43
	.byte	$12
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$26
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$8E
	.byte	$8F
	.byte	$0F
	.byte	$0F
	.byte	$90
	.byte	$91
	.byte	$48
	.byte	$49
	.byte	$0F
	.byte	$4A
	.byte	$4B
	.byte	$4C
	.byte	$0F
	.byte	$AC
	.byte	$02
	.byte	$4D
	.byte	$4E
	.byte	$4F
	.byte	$50
	.byte	$51
	.byte	$36
	.byte	$AC
	.byte	$04
	.byte	$92
	.byte	$93
	.byte	$0F
	.byte	$AC
	.byte	$07
	.byte	$94
	.byte	$43
	.byte	$12
	.byte	$0F
	.byte	$60
	.byte	$95
	.byte	$43
	.byte	$12
	.byte	$73
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$0F
	.byte	$AC
	.byte	$12
	.byte	$A4
	.byte	$A5
	.byte	$12
	.byte	$12
	.byte	$99
	.byte	$9A
	.byte	$12
	.byte	$AC
	.byte	$06
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$9F
	.byte	$A0
	.byte	$A1
	.byte	$0F
	.byte	$AC
	.byte	$09
	.byte	$A6
	.byte	$A7
	.byte	$A5
	.byte	$12
	.byte	$AC
	.byte	$02
	.byte	$A2
	.byte	$AC
	.byte	$11
	.byte	$A8
	.byte	$A9
	.byte	$AC
	.byte	$05
	.byte	$AA
	.byte	$AB
	.byte	$A2
	.byte	$AC
	.byte	$04
	.byte	$A3
	.byte	$AC
	.byte	$FE
	.byte	$A3
	.byte	$AC
	.byte	$60
	.byte	$00
	.byte	$AC
	.byte	$3E
	.byte	$00
	.byte	$AC
	.byte	$00
_lightInDesert:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$61
	.byte	$62
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$64
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$04
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$65
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$06
	.byte	$07
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$66
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0B
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$6B
	.byte	$6C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0C
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$6D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$6E
	.byte	$6F
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$70
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$16
	.byte	$17
	.byte	$18
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$21
	.byte	$00
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$71
	.byte	$72
	.byte	$73
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$28
	.byte	$29
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$2E
	.byte	$2F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$30
	.byte	$7E
	.byte	$7F
	.byte	$80
	.byte	$02
	.byte	$81
	.byte	$82
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$31
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$32
	.byte	$33
	.byte	$34
	.byte	$35
	.byte	$36
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$8E
	.byte	$8F
	.byte	$90
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$1F
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$3C
	.byte	$3D
	.byte	$3E
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$3F
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$43
	.byte	$97
	.byte	$00
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$9B
	.byte	$9C
	.byte	$9C
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$9F
	.byte	$A0
	.byte	$31
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$4C
	.byte	$3E
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A4
	.byte	$A5
	.byte	$A6
	.byte	$00
	.byte	$A7
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$1F
	.byte	$31
	.byte	$1F
	.byte	$4D
	.byte	$4E
	.byte	$4F
	.byte	$50
	.byte	$51
	.byte	$40
	.byte	$52
	.byte	$53
	.byte	$54
	.byte	$00
	.byte	$00
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$AE
	.byte	$AF
	.byte	$B0
	.byte	$B1
	.byte	$B2
	.byte	$00
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$1F
	.byte	$1F
	.byte	$B9
	.byte	$BA
	.byte	$58
	.byte	$59
	.byte	$1F
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$5D
	.byte	$5E
	.byte	$5F
	.byte	$60
	.byte	$3F
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$47
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$BE
	.byte	$BF
	.byte	$00
	.byte	$1F
	.byte	$1F
	.byte	$C0
	.byte	$54
	.byte	$00
	.byte	$00
	.byte	$C1
	.byte	$C2
	.byte	$C3
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$CF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$C4
	.byte	$C5
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$C6
	.byte	$C7
	.byte	$C8
	.byte	$C9
	.byte	$CA
	.byte	$CB
	.byte	$CC
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$1F
	.byte	$D0
	.byte	$D1
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$CE
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_the3Heroes:
	.byte	$00
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$02
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$10
	.byte	$11
	.byte	$12
	.byte	$09
	.byte	$09
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$16
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$17
	.byte	$00
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$18
	.byte	$19
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$21
	.byte	$09
	.byte	$09
	.byte	$13
	.byte	$14
	.byte	$09
	.byte	$22
	.byte	$23
	.byte	$09
	.byte	$09
	.byte	$24
	.byte	$0B
	.byte	$09
	.byte	$17
	.byte	$25
	.byte	$09
	.byte	$09
	.byte	$26
	.byte	$27
	.byte	$20
	.byte	$28
	.byte	$09
	.byte	$29
	.byte	$1A
	.byte	$2A
	.byte	$2B
	.byte	$1D
	.byte	$2C
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$2D
	.byte	$09
	.byte	$09
	.byte	$13
	.byte	$14
	.byte	$09
	.byte	$2E
	.byte	$2F
	.byte	$30
	.byte	$31
	.byte	$12
	.byte	$32
	.byte	$33
	.byte	$34
	.byte	$25
	.byte	$09
	.byte	$09
	.byte	$35
	.byte	$36
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$1A
	.byte	$3B
	.byte	$09
	.byte	$3C
	.byte	$3D
	.byte	$3E
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$3F
	.byte	$40
	.byte	$09
	.byte	$41
	.byte	$05
	.byte	$42
	.byte	$43
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$44
	.byte	$09
	.byte	$45
	.byte	$46
	.byte	$25
	.byte	$09
	.byte	$09
	.byte	$47
	.byte	$48
	.byte	$20
	.byte	$49
	.byte	$09
	.byte	$3A
	.byte	$1A
	.byte	$3B
	.byte	$09
	.byte	$09
	.byte	$4A
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$4B
	.byte	$4C
	.byte	$41
	.byte	$05
	.byte	$4D
	.byte	$4E
	.byte	$20
	.byte	$20
	.byte	$4F
	.byte	$50
	.byte	$51
	.byte	$09
	.byte	$52
	.byte	$25
	.byte	$09
	.byte	$09
	.byte	$53
	.byte	$20
	.byte	$20
	.byte	$54
	.byte	$55
	.byte	$3A
	.byte	$1A
	.byte	$56
	.byte	$09
	.byte	$57
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$5C
	.byte	$5D
	.byte	$20
	.byte	$5E
	.byte	$5F
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$25
	.byte	$09
	.byte	$63
	.byte	$64
	.byte	$20
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$1A
	.byte	$69
	.byte	$09
	.byte	$6A
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$6B
	.byte	$54
	.byte	$6C
	.byte	$41
	.byte	$6D
	.byte	$6E
	.byte	$6F
	.byte	$70
	.byte	$20
	.byte	$71
	.byte	$09
	.byte	$72
	.byte	$73
	.byte	$74
	.byte	$25
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$20
	.byte	$78
	.byte	$09
	.byte	$09
	.byte	$79
	.byte	$1A
	.byte	$7A
	.byte	$7B
	.byte	$27
	.byte	$7C
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$7D
	.byte	$7E
	.byte	$09
	.byte	$7F
	.byte	$6D
	.byte	$80
	.byte	$01
	.byte	$81
	.byte	$82
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$01
	.byte	$74
	.byte	$25
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$20
	.byte	$89
	.byte	$09
	.byte	$09
	.byte	$79
	.byte	$1A
	.byte	$69
	.byte	$8A
	.byte	$20
	.byte	$8B
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$8C
	.byte	$09
	.byte	$8D
	.byte	$6D
	.byte	$01
	.byte	$8E
	.byte	$20
	.byte	$20
	.byte	$8F
	.byte	$90
	.byte	$09
	.byte	$91
	.byte	$92
	.byte	$25
	.byte	$09
	.byte	$93
	.byte	$94
	.byte	$20
	.byte	$95
	.byte	$96
	.byte	$09
	.byte	$79
	.byte	$02
	.byte	$69
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$9A
	.byte	$9B
	.byte	$09
	.byte	$8D
	.byte	$FF
	.byte	$9D
	.byte	$9E
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$7D
	.byte	$09
	.byte	$9F
	.byte	$92
	.byte	$25
	.byte	$09
	.byte	$A0
	.byte	$A1
	.byte	$95
	.byte	$A2
	.byte	$A3
	.byte	$09
	.byte	$A4
	.byte	$FF
	.byte	$69
	.byte	$09
	.byte	$57
	.byte	$9A
	.byte	$20
	.byte	$20
	.byte	$A5
	.byte	$A2
	.byte	$89
	.byte	$A6
	.byte	$09
	.byte	$8D
	.byte	$FF
	.byte	$A7
	.byte	$A8
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$A9
	.byte	$AA
	.byte	$92
	.byte	$25
	.byte	$09
	.byte	$AB
	.byte	$AC
	.byte	$20
	.byte	$AD
	.byte	$AE
	.byte	$09
	.byte	$A4
	.byte	$FF
	.byte	$7A
	.byte	$09
	.byte	$AF
	.byte	$B0
	.byte	$B1
	.byte	$B2
	.byte	$09
	.byte	$B3
	.byte	$20
	.byte	$A3
	.byte	$09
	.byte	$B4
	.byte	$FF
	.byte	$B5
	.byte	$B6
	.byte	$20
	.byte	$20
	.byte	$9A
	.byte	$B7
	.byte	$1D
	.byte	$B8
	.byte	$92
	.byte	$25
	.byte	$29
	.byte	$B9
	.byte	$29
	.byte	$20
	.byte	$BA
	.byte	$AE
	.byte	$09
	.byte	$A4
	.byte	$FF
	.byte	$69
	.byte	$09
	.byte	$BB
	.byte	$BC
	.byte	$20
	.byte	$BD
	.byte	$09
	.byte	$BE
	.byte	$20
	.byte	$BF
	.byte	$09
	.byte	$B4
	.byte	$FF
	.byte	$C1
	.byte	$20
	.byte	$20
	.byte	$C2
	.byte	$C3
	.byte	$C4
	.byte	$C5
	.byte	$C6
	.byte	$52
	.byte	$25
	.byte	$09
	.byte	$C7
	.byte	$C8
	.byte	$20
	.byte	$C9
	.byte	$CA
	.byte	$09
	.byte	$A4
	.byte	$FF
	.byte	$CB
	.byte	$09
	.byte	$09
	.byte	$BE
	.byte	$20
	.byte	$CC
	.byte	$09
	.byte	$CD
	.byte	$20
	.byte	$CE
	.byte	$09
	.byte	$B4
	.byte	$FF
	.byte	$CF
	.byte	$01
	.byte	$D0
	.byte	$D1
	.byte	$D2
	.byte	$12
	.byte	$09
	.byte	$D3
	.byte	$92
	.byte	$D4
	.byte	$96
	.byte	$D5
	.byte	$D6
	.byte	$D7
	.byte	$D8
	.byte	$D9
	.byte	$DA
	.byte	$DB
	.byte	$FF
	.byte	$DC
	.byte	$0B
	.byte	$DD
	.byte	$DE
	.byte	$DF
	.byte	$09
	.byte	$09
	.byte	$E0
	.byte	$E1
	.byte	$E2
	.byte	$E3
	.byte	$E4
	.byte	$FF
	.byte	$E5
	.byte	$E6
	.byte	$E7
	.byte	$09
	.byte	$09
	.byte	$E8
	.byte	$09
	.byte	$09
	.byte	$E9
	.byte	$FF
	.byte	$EA
	.byte	$EB
	.byte	$EC
	.byte	$ED
	.byte	$ED
	.byte	$EE
	.byte	$EF
	.byte	$F0
	.byte	$FF
	.byte	$FF
	.byte	$F1
	.byte	$EB
	.byte	$EC
	.byte	$ED
	.byte	$F2
	.byte	$F2
	.byte	$ED
	.byte	$F3
	.byte	$F4
	.byte	$F5
	.byte	$F6
	.byte	$FF
	.byte	$F7
	.byte	$F8
	.byte	$F9
	.byte	$FA
	.byte	$FA
	.byte	$F3
	.byte	$FB
	.byte	$FC
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FD
	.byte	$FD
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FD
	.byte	$FE
	.byte	$FE
	.byte	$FE
	.byte	$9C
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FD
	.byte	$FD
	.byte	$9C
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_the3Heroes_attr:
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$55
	.byte	$55
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$55
	.byte	$55
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$55
	.byte	$55
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$55
	.byte	$55
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$44
	.byte	$55
	.byte	$55
	.byte	$99
	.byte	$AA
	.byte	$AA
_sealAngelHeaven:
	.byte	$98
	.byte	$00
	.byte	$98
	.byte	$0A
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$98
	.byte	$05
	.byte	$41
	.byte	$42
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$04
	.byte	$02
	.byte	$03
	.byte	$98
	.byte	$05
	.byte	$43
	.byte	$44
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$05
	.byte	$02
	.byte	$03
	.byte	$98
	.byte	$06
	.byte	$45
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$04
	.byte	$02
	.byte	$03
	.byte	$98
	.byte	$02
	.byte	$46
	.byte	$03
	.byte	$98
	.byte	$02
	.byte	$47
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$06
	.byte	$02
	.byte	$07
	.byte	$08
	.byte	$03
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$45
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$03
	.byte	$4C
	.byte	$4D
	.byte	$4E
	.byte	$4F
	.byte	$50
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$04
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$10
	.byte	$51
	.byte	$52
	.byte	$53
	.byte	$03
	.byte	$54
	.byte	$00
	.byte	$98
	.byte	$15
	.byte	$04
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$12
	.byte	$55
	.byte	$56
	.byte	$03
	.byte	$03
	.byte	$57
	.byte	$00
	.byte	$98
	.byte	$0F
	.byte	$13
	.byte	$14
	.byte	$15
	.byte	$16
	.byte	$98
	.byte	$02
	.byte	$17
	.byte	$03
	.byte	$98
	.byte	$02
	.byte	$18
	.byte	$58
	.byte	$59
	.byte	$03
	.byte	$03
	.byte	$5A
	.byte	$16
	.byte	$98
	.byte	$03
	.byte	$00
	.byte	$98
	.byte	$08
	.byte	$19
	.byte	$1A
	.byte	$1B
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$21
	.byte	$22
	.byte	$03
	.byte	$98
	.byte	$03
	.byte	$5B
	.byte	$03
	.byte	$98
	.byte	$02
	.byte	$5C
	.byte	$5D
	.byte	$5E
	.byte	$5F
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$23
	.byte	$24
	.byte	$00
	.byte	$98
	.byte	$02
	.byte	$25
	.byte	$26
	.byte	$27
	.byte	$11
	.byte	$03
	.byte	$03
	.byte	$28
	.byte	$03
	.byte	$98
	.byte	$07
	.byte	$68
	.byte	$69
	.byte	$03
	.byte	$03
	.byte	$6A
	.byte	$6B
	.byte	$30
	.byte	$6C
	.byte	$6D
	.byte	$6E
	.byte	$6F
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$29
	.byte	$2A
	.byte	$2B
	.byte	$2C
	.byte	$2D
	.byte	$2E
	.byte	$2F
	.byte	$30
	.byte	$31
	.byte	$32
	.byte	$03
	.byte	$98
	.byte	$07
	.byte	$70
	.byte	$71
	.byte	$72
	.byte	$03
	.byte	$73
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$03
	.byte	$98
	.byte	$07
	.byte	$33
	.byte	$34
	.byte	$03
	.byte	$35
	.byte	$03
	.byte	$98
	.byte	$02
	.byte	$36
	.byte	$7B
	.byte	$56
	.byte	$03
	.byte	$03
	.byte	$7C
	.byte	$03
	.byte	$7D
	.byte	$7E
	.byte	$7F
	.byte	$80
	.byte	$81
	.byte	$03
	.byte	$98
	.byte	$0C
	.byte	$37
	.byte	$38
	.byte	$03
	.byte	$39
	.byte	$3A
	.byte	$03
	.byte	$33
	.byte	$3B
	.byte	$82
	.byte	$83
	.byte	$03
	.byte	$84
	.byte	$85
	.byte	$03
	.byte	$86
	.byte	$03
	.byte	$98
	.byte	$16
	.byte	$3C
	.byte	$3D
	.byte	$87
	.byte	$88
	.byte	$03
	.byte	$98
	.byte	$1A
	.byte	$3E
	.byte	$3F
	.byte	$40
	.byte	$00
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$03
	.byte	$98
	.byte	$19
	.byte	$8C
	.byte	$8D
	.byte	$93
	.byte	$94
	.byte	$03
	.byte	$98
	.byte	$1C
	.byte	$8E
	.byte	$95
	.byte	$56
	.byte	$03
	.byte	$98
	.byte	$0D
	.byte	$8F
	.byte	$98
	.byte	$0D
	.byte	$90
	.byte	$91
	.byte	$96
	.byte	$97
	.byte	$8F
	.byte	$98
	.byte	$0D
	.byte	$92
	.byte	$98
	.byte	$FE
	.byte	$92
	.byte	$98
	.byte	$60
	.byte	$00
	.byte	$98
	.byte	$3E
	.byte	$00
	.byte	$98
	.byte	$00
_mensaje1:
	.byte	$46,$6F,$72,$20,$6D,$69,$6C,$6C,$65,$6E,$69,$61,$2C,$20,$4C,$49
	.byte	$47,$48,$54,$20,$61,$6E,$64,$20,$44,$41,$52,$4B,$0A,$0A,$68,$61
	.byte	$76,$65,$20,$6C,$69,$76,$65,$64,$20,$69,$6E,$20,$62,$61,$6C,$61
	.byte	$6E,$63,$65,$2C,$00
_mensaje2:
	.byte	$42,$72,$69,$6E,$67,$69,$6E,$67,$20,$70,$65,$61,$63,$65,$20,$74
	.byte	$6F,$20,$74,$68,$65,$20,$57,$4F,$52,$4C,$44,$2E,$00
_mensaje3:
	.byte	$42,$75,$74,$20,$69,$66,$20,$74,$68,$69,$73,$20,$68,$61,$72,$6D
	.byte	$6F,$6E,$79,$0A,$77,$65,$72,$65,$20,$74,$6F,$20,$73,$68,$61,$74
	.byte	$74,$65,$72,$2E,$2E,$2E,$00
_mensaje4:
	.byte	$41,$20,$74,$65,$72,$72,$69,$62,$6C,$65,$20,$63,$61,$6C,$61,$6D
	.byte	$69,$74,$79,$20,$77,$6F,$75,$6C,$64,$20,$6F,$63,$63,$75,$72,$2E
	.byte	$00
_mensaje5:
	.byte	$54,$68,$65,$20,$73,$6B,$79,$20,$77,$69,$6C,$6C,$20,$72,$75,$6E
	.byte	$0A,$0A,$62,$6C,$61,$63,$6B,$20,$77,$69,$74,$68,$20,$74,$65,$72
	.byte	$72,$6F,$72,$00
_mensaje6:
	.byte	$41,$6E,$64,$20,$74,$68,$65,$20,$6C,$61,$6E,$64,$20,$77,$69,$6C
	.byte	$6C,$0A,$0A,$63,$72,$61,$63,$6B,$20,$77,$69,$74,$68,$20,$66,$65
	.byte	$61,$72,$2E,$00
_mensaje7:
	.byte	$54,$68,$65,$6E,$2C,$20,$68,$65,$72,$20,$68,$65,$61,$72,$74,$20
	.byte	$70,$6F,$75,$6E,$64,$69,$6E,$67,$2E,$2E,$2E,$00
_mensaje8:
	.byte	$54,$68,$65,$20,$45,$41,$52,$54,$48,$20,$77,$69,$6C,$6C,$20,$64
	.byte	$72,$61,$77,$0A,$0A,$68,$65,$72,$20,$66,$69,$6E,$61,$6C,$20,$62
	.byte	$72,$65,$61,$74,$68,$2E,$00
_mensaje9:
	.byte	$4F,$6E,$6C,$79,$20,$74,$68,$65,$6E,$2C,$20,$73,$68,$69,$6E,$69
	.byte	$6E,$67,$20,$77,$69,$74,$68,$20,$68,$6F,$70,$65,$2E,$2E,$2E,$00
_mensaje10:
	.byte	$54,$68,$72,$65,$65,$20,$48,$45,$52,$4F,$45,$53,$20,$61,$70,$70
	.byte	$65,$61,$72,$0A,$0A,$61,$74,$20,$57,$4F,$52,$4C,$44,$53,$27,$20
	.byte	$65,$64,$67,$65,$2E,$00
_mensaje11:
	.byte	$41,$20,$48,$55,$4D,$41,$4E,$2C,$00
_mensaje12:
	.byte	$41,$20,$4D,$4F,$4E,$53,$54,$45,$52,$2C,$00
_mensaje13:
	.byte	$41,$6E,$64,$20,$61,$20,$50,$52,$49,$4E,$43,$45,$0A,$0A,$46,$52
	.byte	$4F,$4D,$20,$54,$48,$45,$20,$44,$41,$52,$4B,$00
_mensaje14:
	.byte	$4F,$6E,$6C,$79,$20,$74,$68,$65,$79,$20,$63,$61,$6E,$20,$73,$65
	.byte	$61,$6C,$20,$74,$68,$65,$20,$66,$6F,$75,$6E,$74,$61,$69,$6E,$73
	.byte	$00
_mensaje15:
	.byte	$41,$6E,$64,$20,$62,$61,$6E,$69,$73,$68,$20,$74,$68,$65,$20,$41
	.byte	$4E,$47,$45,$4C,$27,$53,$20,$48,$45,$41,$56,$45,$4E,$2E,$00
_mensaje16:
	.byte	$4F,$6E,$6C,$79,$20,$74,$68,$65,$6E,$20,$77,$69,$6C,$6C,$20,$62
	.byte	$61,$6C,$61,$6E,$63,$65,$0A,$0A,$62,$65,$20,$72,$65,$73,$74,$6F
	.byte	$72,$65,$64,$2C,$00
_mensaje17:
	.byte	$41,$6E,$64,$20,$3E,$74,$68,$65,$20,$57,$4F,$52,$4C,$44,$20,$3E
	.byte	$73,$61,$76,$65,$64,$0A,$0A,$3E,$66,$72,$6F,$6D,$20,$64,$65,$73
	.byte	$74,$72,$3E,$75,$63,$74,$69,$6F,$6E,$2E,$00

.segment	"BSS"

_bankLevel:
	.res	1,$00
_bankBuffer:
	.res	10,$00
.segment	"ZEROPAGE"
_i:
	.res	1,$00
_fi:
	.res	1,$00
_fj:
	.res	1,$00
_fk:
	.res	1,$00
_fi16:
	.res	2,$00
.segment	"BSS"
_irq_buffer:
	.res	32,$00
.segment	"XRAM"
_wram_array:
	.res	8192,$00

; ---------------------------------------------------------------
; void __near__ custom_fade_in (unsigned char palNo, unsigned char time)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_custom_fade_in: near

	.dbg	func, "custom_fade_in", "00", static, "_custom_fade_in"
	.dbg	sym, "palNo", "00", auto, 1
	.dbg	sym, "time", "00", auto, 0

.segment	"CODE"

;
; void custom_fade_in(u8 palNo, u8 time){
;
	.dbg	line, "fullbg.c", 64
	jsr     pusha
;
; for (fi = 1; fi <= 3; ++fi){
;
	.dbg	line, "fullbg.c", 65
	lda     #$01
	sta     _fi
L0010:	lda     _fi
	cmp     #$04
	bcs     L0003
;
; for (fj = 0; fj < fi; ++fj){
;
	.dbg	line, "fullbg.c", 66
	lda     #$00
	sta     _fj
L0011:	lda     _fj
	cmp     _fi
	bcs     L0007
;
; fk = palNo*4+3-fj;
;
	.dbg	line, "fullbg.c", 67
	ldy     #$01
	lda     (sp),y
	asl     a
	asl     a
	clc
	adc     #$03
	sec
	sbc     _fj
	sta     _fk
;
; if(palette[fk] == 0x0f){
;
	.dbg	line, "fullbg.c", 68
	ldy     _fk
	lda     _palette,y
	cmp     #$0F
	bne     L000B
;
; palette[fk] = 0x07;
;
	.dbg	line, "fullbg.c", 69
	ldy     _fk
	lda     #$07
	sta     _palette,y
;
; }else{
;
	.dbg	line, "fullbg.c", 70
	jmp     L0012
;
; palette[fk] += 0x10;
;
	.dbg	line, "fullbg.c", 71
L000B:	lda     #<(_palette)
	ldx     #>(_palette)
	clc
	adc     _fk
	bcc     L000F
	inx
L000F:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	clc
	adc     #$10
	sta     (ptr1),y
;
; for (fj = 0; fj < fi; ++fj){
;
	.dbg	line, "fullbg.c", 66
L0012:	inc     _fj
	jmp     L0011
;
; delay(time);
;
	.dbg	line, "fullbg.c", 74
L0007:	ldy     #$00
	lda     (sp),y
	jsr     _delay
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 75
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; for (fi = 1; fi <= 3; ++fi){
;
	.dbg	line, "fullbg.c", 65
	inc     _fi
	jmp     L0010
;
; }
;
	.dbg	line, "fullbg.c", 77
L0003:	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ load_nametable_a_during_vblank (const unsigned char *table, unsigned int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_nametable_a_during_vblank: near

	.dbg	func, "load_nametable_a_during_vblank", "00", static, "_load_nametable_a_during_vblank"
	.dbg	sym, "table", "00", auto, 2
	.dbg	sym, "length", "00", auto, 0

.segment	"CODE"

;
; void load_nametable_a_during_vblank(const unsigned char* table, u16 length){
;
	.dbg	line, "fullbg.c", 78
	jsr     pushax
;
; fi16 = 0;
;
	.dbg	line, "fullbg.c", 79
	lda     #$00
	sta     _fi16
	sta     _fi16+1
;
; while(fi16 < length){ //NT_A+FULL 1024 B without changing palette
;
	.dbg	line, "fullbg.c", 80
	jmp     L0004
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 81
L0002:	ldx     #$00
	txa
	jsr     _set_vram_update
;
; nameTableLoader[0] = MSB(fi16 + NAMETABLE_A) | NT_UPD_HORZ;
;
	.dbg	line, "fullbg.c", 82
	lda     _fi16+1
	clc
	adc     #$20
	ora     #$40
	sta     _nameTableLoader
;
; nameTableLoader[1] = LSB(fi16 + NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 83
	lda     _fi16
	sta     _nameTableLoader+1
	lda     _fi16+1
	clc
	adc     #$20
;
; for (fi = 0; fi<64; ++fi){
;
	.dbg	line, "fullbg.c", 84
	lda     #$00
	sta     _fi
L000C:	lda     _fi
	cmp     #$40
	bcs     L0006
;
; nameTableLoader[fi+3] = table[fi16];
;
	.dbg	line, "fullbg.c", 85
	ldx     #$00
	lda     _fi
	clc
	adc     #$03
	bcc     L000B
	inx
	clc
L000B:	adc     #<(_nameTableLoader)
	sta     sreg
	txa
	adc     #>(_nameTableLoader)
	sta     sreg+1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     _fi16
	sta     ptr1
	txa
	adc     _fi16+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
;
; ++fi16;
;
	.dbg	line, "fullbg.c", 86
	inc     _fi16
	bne     L000A
	inc     _fi16+1
;
; for (fi = 0; fi<64; ++fi){
;
	.dbg	line, "fullbg.c", 84
L000A:	inc     _fi
	jmp     L000C
;
; set_vram_update(nameTableLoader);
;
	.dbg	line, "fullbg.c", 88
L0006:	lda     #<(_nameTableLoader)
	ldx     #>(_nameTableLoader)
	jsr     _set_vram_update
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 89
	jsr     _ppu_wait_nmi
;
; while(fi16 < length){ //NT_A+FULL 1024 B without changing palette
;
	.dbg	line, "fullbg.c", 80
L0004:	lda     _fi16
	ldy     #$00
	cmp     (sp),y
	lda     _fi16+1
	iny
	sbc     (sp),y
	bcc     L0002
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 91
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; }
;
	.dbg	line, "fullbg.c", 92
	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ fade_in (unsigned char time)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fade_in: near

	.dbg	func, "fade_in", "00", static, "_fade_in"
	.dbg	sym, "time", "00", auto, 0

.segment	"CODE"

;
; void fade_in(u8 time){ // From black to normal
;
	.dbg	line, "fullbg.c", 93
	jsr     pusha
;
; for (fi = 0; fi<4; ++fi){
;
	.dbg	line, "fullbg.c", 94
	lda     #$00
	sta     _fi
L0007:	lda     _fi
	cmp     #$04
	bcs     L0003
;
; delay(time);
;
	.dbg	line, "fullbg.c", 95
	ldy     #$00
	lda     (sp),y
	jsr     _delay
;
; pal_fade_to(fi, fi+1);
;
	.dbg	line, "fullbg.c", 96
	lda     _fi
	jsr     pusha
	lda     _fi
	clc
	adc     #$01
	jsr     _pal_fade_to
;
; for (fi = 0; fi<4; ++fi){
;
	.dbg	line, "fullbg.c", 94
	inc     _fi
	jmp     L0007
;
; }
;
	.dbg	line, "fullbg.c", 98
L0003:	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ fade_out (unsigned char time)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fade_out: near

	.dbg	func, "fade_out", "00", static, "_fade_out"
	.dbg	sym, "time", "00", auto, 0

.segment	"CODE"

;
; void fade_out(u8 time){ //From normal to black
;
	.dbg	line, "fullbg.c", 99
	jsr     pusha
;
; for (fi = 4; fi > 0; --fi){
;
	.dbg	line, "fullbg.c", 100
	lda     #$04
	sta     _fi
L0007:	lda     _fi
	beq     L0003
;
; delay(time);
;
	.dbg	line, "fullbg.c", 101
	ldy     #$00
	lda     (sp),y
	jsr     _delay
;
; pal_fade_to(fi, fi-1);
;
	.dbg	line, "fullbg.c", 102
	lda     _fi
	jsr     pusha
	lda     _fi
	sec
	sbc     #$01
	jsr     _pal_fade_to
;
; for (fi = 4; fi > 0; --fi){
;
	.dbg	line, "fullbg.c", 100
	dec     _fi
	jmp     L0007
;
; }
;
	.dbg	line, "fullbg.c", 104
L0003:	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ fade_out_white (unsigned char time)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fade_out_white: near

	.dbg	func, "fade_out_white", "00", static, "_fade_out_white"
	.dbg	sym, "time", "00", auto, 0

.segment	"CODE"

;
; void fade_out_white(u8 time){ //From normal to white
;
	.dbg	line, "fullbg.c", 105
	jsr     pusha
;
; for (fi = 4; fi < 8; ++fi){
;
	.dbg	line, "fullbg.c", 106
	lda     #$04
	sta     _fi
L0007:	lda     _fi
	cmp     #$08
	bcs     L0003
;
; delay(time);
;
	.dbg	line, "fullbg.c", 107
	ldy     #$00
	lda     (sp),y
	jsr     _delay
;
; pal_fade_to(fi, fi+1);
;
	.dbg	line, "fullbg.c", 108
	lda     _fi
	jsr     pusha
	lda     _fi
	clc
	adc     #$01
	jsr     _pal_fade_to
;
; for (fi = 4; fi < 8; ++fi){
;
	.dbg	line, "fullbg.c", 106
	inc     _fi
	jmp     L0007
;
; }
;
	.dbg	line, "fullbg.c", 110
L0003:	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ fade_in_white (unsigned char time)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fade_in_white: near

	.dbg	func, "fade_in_white", "00", static, "_fade_in_white"
	.dbg	sym, "time", "00", auto, 0

.segment	"CODE"

;
; void fade_in_white(u8 time){ //From white to normal
;
	.dbg	line, "fullbg.c", 111
	jsr     pusha
;
; for (fi = 8; fi > 4; --fi){
;
	.dbg	line, "fullbg.c", 112
	lda     #$08
	sta     _fi
L0007:	lda     _fi
	cmp     #$05
	bcc     L0003
;
; delay(time);
;
	.dbg	line, "fullbg.c", 113
	ldy     #$00
	lda     (sp),y
	jsr     _delay
;
; pal_fade_to(fi, fi-1);
;
	.dbg	line, "fullbg.c", 114
	lda     _fi
	jsr     pusha
	lda     _fi
	sec
	sbc     #$01
	jsr     _pal_fade_to
;
; for (fi = 8; fi > 4; --fi){
;
	.dbg	line, "fullbg.c", 112
	dec     _fi
	jmp     L0007
;
; }
;
	.dbg	line, "fullbg.c", 116
L0003:	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ map_to (unsigned char image)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_map_to: near

	.dbg	func, "map_to", "00", static, "_map_to"
	.dbg	sym, "image", "00", auto, 0

.segment	"CODE"

;
; void map_to(u8 image){ // Changes the tileset of BG 0 and updates the irq
;
	.dbg	line, "fullbg.c", 117
	jsr     pusha
;
; disable_irq();
;
	.dbg	line, "fullbg.c", 118
	jsr     _disable_irq
;
; set_chr_mode_0(image);
;
	.dbg	line, "fullbg.c", 119
	ldy     #$00
	lda     (sp),y
	jsr     _set_chr_mode_0
;
; set_chr_mode_1(image+1);
;
	.dbg	line, "fullbg.c", 120
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$01
	jsr     _set_chr_mode_1
;
; set_chr_mode_2(image+2);
;
	.dbg	line, "fullbg.c", 121
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$02
	jsr     _set_chr_mode_2
;
; set_chr_mode_3(image+3);
;
	.dbg	line, "fullbg.c", 122
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$03
	jsr     _set_chr_mode_3
;
; irq_buffer[1] = image;
;
	.dbg	line, "fullbg.c", 123
	ldy     #$00
	lda     (sp),y
	sta     _irq_buffer+1
;
; irq_buffer[3] = image+1;
;
	.dbg	line, "fullbg.c", 124
	lda     (sp),y
	clc
	adc     #$01
	sta     _irq_buffer+3
;
; set_irq_ptr(irq_buffer);
;
	.dbg	line, "fullbg.c", 125
	lda     #<(_irq_buffer)
	ldx     #>(_irq_buffer)
	jsr     _set_irq_ptr
;
; }
;
	.dbg	line, "fullbg.c", 126
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ fix_text_color (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fix_text_color: near

	.dbg	func, "fix_text_color", "00", static, "_fix_text_color"

.segment	"CODE"

;
; fi = 0;
;
	.dbg	line, "fullbg.c", 128
	lda     #$00
	sta     _fi
;
; vram_adr(0x23E8);
;
	.dbg	line, "fullbg.c", 129
	ldx     #$23
	lda     #$E8
	jsr     _vram_adr
;
; for (fi = 0; fi < 16; ++fi){
;
	.dbg	line, "fullbg.c", 130
	lda     #$00
	sta     _fi
L0006:	lda     _fi
	cmp     #$10
	bcs     L0003
;
; vram_put(0xFF);
;
	.dbg	line, "fullbg.c", 131
	lda     #$FF
	jsr     _vram_put
;
; for (fi = 0; fi < 16; ++fi){
;
	.dbg	line, "fullbg.c", 130
	inc     _fi
	jmp     L0006
;
; }
;
	.dbg	line, "fullbg.c", 133
L0003:	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ print (const char *message, unsigned char x, unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print: near

	.dbg	func, "print", "00", static, "_print"
	.dbg	sym, "message", "00", auto, 2
	.dbg	sym, "x", "00", auto, 1
	.dbg	sym, "y", "00", auto, 0

.segment	"CODE"

;
; void print(const char* message, u8 x, u8 y){
;
	.dbg	line, "fullbg.c", 135
	jsr     pusha
;
; fi = 0; //fi is the index for the message
;
	.dbg	line, "fullbg.c", 136
	lda     #$00
	sta     _fi
;
; fj = 0; //fj is the line count
;
	.dbg	line, "fullbg.c", 137
	sta     _fj
;
; fi16 = NTADR_A(x, y);
;
	.dbg	line, "fullbg.c", 138
	tax
	lda     (sp,x)
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	ora     ptr1
	sta     _fi16
	lda     tmp1
	ora     #$20
	sta     _fi16+1
;
; --fi16;
;
	.dbg	line, "fullbg.c", 139
	ldx     _fi16
	bne     L0002
	dec     _fi16+1
L0002:	dex
	stx     _fi16
;
; mandador[0] = MSB(fi16) | NT_UPD_HORZ;
;
	.dbg	line, "fullbg.c", 140
	lda     _fi16+1
	ora     #$40
	sta     _mandador
;
; mandador[1] = LSB(fi16);
;
	.dbg	line, "fullbg.c", 141
	lda     _fi16
	sta     _mandador+1
;
; while(message[fi]){
;
	.dbg	line, "fullbg.c", 142
	jmp     L0005
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 143
L0003:	jsr     _ppu_wait_nmi
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 144
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; if(message[fi] == '\n'){
;
	.dbg	line, "fullbg.c", 145
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _fi
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$0A
	bne     L0006
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 146
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; mandador[1] = LSB(fi16) + 32 * ++fj;
;
	.dbg	line, "fullbg.c", 147
	ldx     #$00
	inc     _fj
	lda     _fj
	jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     _fi16
	sta     _mandador+1
;
; if(fj >= 8){
;
	.dbg	line, "fullbg.c", 148
	lda     _fj
	cmp     #$08
	jcc     L001B
;
; fj = 0;
;
	.dbg	line, "fullbg.c", 149
	lda     #$00
	sta     _fj
;
; ++mandador[0];
;
	.dbg	line, "fullbg.c", 150
	inc     _mandador
;
; }else if (message[fi] == '>'){
;
	.dbg	line, "fullbg.c", 152
	jmp     L001B
L0006:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _fi
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$3E
	bne     L0009
;
; for (fk = 0; fk < 4; ++fk){
;
	.dbg	line, "fullbg.c", 153
	lda     #$00
	sta     _fk
L0019:	lda     _fk
	cmp     #$04
	bcs     L000B
;
; if(palette[fk] <= 0x0f){
;
	.dbg	line, "fullbg.c", 154
	ldy     _fk
	lda     _palette,y
	cmp     #$10
	bcs     L000E
;
; palette[fk] = 0x0f;
;
	.dbg	line, "fullbg.c", 155
	ldy     _fk
	lda     #$0F
	sta     _palette,y
;
; }else{
;
	.dbg	line, "fullbg.c", 156
	jmp     L001A
;
; palette[fk] -= 0x10;
;
	.dbg	line, "fullbg.c", 157
L000E:	lda     #<(_palette)
	ldx     #>(_palette)
	clc
	adc     _fk
	bcc     L0012
	inx
L0012:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sec
	sbc     #$10
	sta     (ptr1),y
;
; for (fk = 0; fk < 4; ++fk){
;
	.dbg	line, "fullbg.c", 153
L001A:	inc     _fk
	jmp     L0019
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 160
L000B:	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; }else{
;
	.dbg	line, "fullbg.c", 161
	jmp     L001B
;
; mandador[3] = message[fi];
;
	.dbg	line, "fullbg.c", 162
L0009:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _fi
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     _mandador+3
;
; ++mandador[1];
;
	.dbg	line, "fullbg.c", 163
	inc     _mandador+1
;
; set_vram_update(mandador);
;
	.dbg	line, "fullbg.c", 164
	lda     #<(_mandador)
	ldx     #>(_mandador)
	jsr     _set_vram_update
;
; delay(delay_time);
;
	.dbg	line, "fullbg.c", 165
	lda     _delay_time
	jsr     _delay
;
; ++fi;
;
	.dbg	line, "fullbg.c", 167
L001B:	inc     _fi
;
; while(message[fi]){
;
	.dbg	line, "fullbg.c", 142
L0005:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     _fi
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jne     L0003
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 169
	jsr     _ppu_wait_nmi
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 170
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; }
;
	.dbg	line, "fullbg.c", 171
	jmp     incsp4

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ clear_4_lines (unsigned char line)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_4_lines: near

	.dbg	func, "clear_4_lines", "00", static, "_clear_4_lines"
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

;
; void clear_4_lines(u8 line){
;
	.dbg	line, "fullbg.c", 172
	jsr     pusha
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 173
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; fi16 = NTADR_A(0, line);
;
	.dbg	line, "fullbg.c", 174
	ldx     #$00
	lda     (sp,x)
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     _fi16
	lda     tmp1
	ora     #$20
	sta     _fi16+1
;
; clear[0] = MSB(fi16) | NT_UPD_HORZ;
;
	.dbg	line, "fullbg.c", 175
	ora     #$40
	sta     _clear
;
; clear[1] = LSB(fi16);
;
	.dbg	line, "fullbg.c", 176
	lda     _fi16
	sta     _clear+1
;
; set_vram_update(clear);
;
	.dbg	line, "fullbg.c", 177
	lda     #<(_clear)
	ldx     #>(_clear)
	jsr     _set_vram_update
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 178
	jsr     _ppu_wait_nmi
;
; fi16 += 64;
;
	.dbg	line, "fullbg.c", 179
	lda     #$40
	clc
	adc     _fi16
	sta     _fi16
	bcc     L0002
	inc     _fi16+1
;
; clear[0] = MSB(fi16) | NT_UPD_HORZ;
;
	.dbg	line, "fullbg.c", 180
L0002:	lda     _fi16+1
	ora     #$40
	sta     _clear
;
; clear[1] = LSB(fi16);
;
	.dbg	line, "fullbg.c", 181
	lda     _fi16
	sta     _clear+1
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 182
	jsr     _ppu_wait_nmi
;
; set_vram_update(NULL);
;
	.dbg	line, "fullbg.c", 183
	ldx     #$00
	txa
	jsr     _set_vram_update
;
; }
;
	.dbg	line, "fullbg.c", 184
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ change_std_scanline (unsigned char line)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_change_std_scanline: near

	.dbg	func, "change_std_scanline", "00", static, "_change_std_scanline"
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

;
; void change_std_scanline(u8 line){
;
	.dbg	line, "fullbg.c", 185
	jsr     pusha
;
; while(!is_irq_done()){}
;
	.dbg	line, "fullbg.c", 186
L0002:	jsr     _is_irq_done
	tax
	beq     L0002
;
; irq_buffer[4] = line;
;
	.dbg	line, "fullbg.c", 187
	ldy     #$00
	lda     (sp),y
	sta     _irq_buffer+4
;
; }
;
	.dbg	line, "fullbg.c", 188
	jmp     incsp1

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

;
; ppu_off(); // screen off
;
	.dbg	line, "fullbg.c", 190
	jsr     _ppu_off
;
; bank_spr(1); //WARNING: bg map must be 0 and spr bank must be 1 for IRQ to work in real HW
;
	.dbg	line, "fullbg.c", 191
	lda     #$01
	jsr     _bank_spr
;
; pal_bg(palette); // load the palette
;
	.dbg	line, "fullbg.c", 193
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; disable_irq();
;
	.dbg	line, "fullbg.c", 194
	jsr     _disable_irq
;
; irq_buffer[0] = 0xF9; //set_chr_2
;
	.dbg	line, "fullbg.c", 196
	lda     #$F9
	sta     _irq_buffer
;
; irq_buffer[1] = 0; // ... to the 1st quarter of the current image
;
	.dbg	line, "fullbg.c", 197
	lda     #$00
	sta     _irq_buffer+1
;
; irq_buffer[2] = 0xFA; //set_chr_3
;
	.dbg	line, "fullbg.c", 198
	lda     #$FA
	sta     _irq_buffer+2
;
; irq_buffer[3] = 1; // ... to the 2nd quarter of the current image
;
	.dbg	line, "fullbg.c", 199
	lda     #$01
	sta     _irq_buffer+3
;
; irq_buffer[4] = 150; // at scanline 150
;
	.dbg	line, "fullbg.c", 200
	lda     #$96
	sta     _irq_buffer+4
;
; irq_buffer[5] = 0xF9; // set_chr_2
;
	.dbg	line, "fullbg.c", 201
	lda     #$F9
	sta     _irq_buffer+5
;
; irq_buffer[6] = 4; // to the 1st quarter of the text map
;
	.dbg	line, "fullbg.c", 202
	lda     #$04
	sta     _irq_buffer+6
;
; irq_buffer[7] = 0xFA; // set_chr_3
;
	.dbg	line, "fullbg.c", 203
	lda     #$FA
	sta     _irq_buffer+7
;
; irq_buffer[8] = 5; // to the 2nd quarter of the text map
;
	.dbg	line, "fullbg.c", 204
	lda     #$05
	sta     _irq_buffer+8
;
; irq_buffer[9] = 0xFF; //end
;
	.dbg	line, "fullbg.c", 205
	lda     #$FF
	sta     _irq_buffer+9
;
; map_to(ALLOK);
;
	.dbg	line, "fullbg.c", 208
L0002:	lda     #$00
	jsr     _map_to
;
; vram_adr(NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 209
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_unrle(allOk);
;
	.dbg	line, "fullbg.c", 210
	lda     #<(_allOk)
	ldx     #>(_allOk)
	jsr     _vram_unrle
;
; fix_text_color();
;
	.dbg	line, "fullbg.c", 212
	jsr     _fix_text_color
;
; palette[1] = 0x0f;
;
	.dbg	line, "fullbg.c", 213
	lda     #$0F
	sta     _palette+1
;
; palette[3] = 0x17;
;
	.dbg	line, "fullbg.c", 214
	lda     #$17
	sta     _palette+3
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 215
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; pal_bright(0);
;
	.dbg	line, "fullbg.c", 216
	lda     #$00
	jsr     _pal_bright
;
; set_irq_ptr(irq_buffer);
;
	.dbg	line, "fullbg.c", 217
	lda     #<(_irq_buffer)
	ldx     #>(_irq_buffer)
	jsr     _set_irq_ptr
;
; ppu_on_all();
;
	.dbg	line, "fullbg.c", 218
	jsr     _ppu_on_all
;
; fade_in(10);
;
	.dbg	line, "fullbg.c", 220
	lda     #$0A
	jsr     _fade_in
;
; print(mensaje1, 2, 20);
;
	.dbg	line, "fullbg.c", 222
	jsr     decsp3
	lda     #<(_mensaje1)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje1)
	sta     (sp),y
	tya
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 223
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 225
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje2, 2, 20);
;
	.dbg	line, "fullbg.c", 226
	jsr     decsp3
	lda     #<(_mensaje2)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje2)
	sta     (sp),y
	tya
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 227
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 230
	lda     #$14
	jsr     _clear_4_lines
;
; palette[1] = 0x17;
;
	.dbg	line, "fullbg.c", 231
	lda     #$17
	sta     _palette+1
;
; palette[3] = 0x0f;
;
	.dbg	line, "fullbg.c", 232
	lda     #$0F
	sta     _palette+3
;
; pal_fade_to(4, 8);
;
	.dbg	line, "fullbg.c", 233
	lda     #$04
	jsr     pusha
	lda     #$08
	jsr     _pal_fade_to
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 234
	jsr     _ppu_wait_nmi
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 235
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; pal_fade_to(8,4);
;
	.dbg	line, "fullbg.c", 236
	lda     #$08
	jsr     pusha
	lda     #$04
	jsr     _pal_fade_to
;
; print(mensaje3, 5, 20);
;
	.dbg	line, "fullbg.c", 238
	jsr     decsp3
	lda     #<(_mensaje3)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje3)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 239
	lda     #$32
	jsr     _delay
;
; fade_out(1);
;
	.dbg	line, "fullbg.c", 240
	lda     #$01
	jsr     _fade_out
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 241
	jsr     _ppu_off
;
; palette[3] = 0x30;
;
	.dbg	line, "fullbg.c", 242
	lda     #$30
	sta     _palette+3
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 244
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; vram_adr(NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 245
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_fill(0xFF, 0x3C0);
;
	.dbg	line, "fullbg.c", 246
	lda     #$FF
	jsr     pusha
	ldx     #$03
	lda     #$C0
	jsr     _vram_fill
;
; ppu_on_all();
;
	.dbg	line, "fullbg.c", 247
	jsr     _ppu_on_all
;
; pal_bright(4);
;
	.dbg	line, "fullbg.c", 248
	lda     #$04
	jsr     _pal_bright
;
; change_std_scanline(20);
;
	.dbg	line, "fullbg.c", 249
	lda     #$14
	jsr     _change_std_scanline
;
; print(mensaje4, 0, 10);
;
	.dbg	line, "fullbg.c", 251
	jsr     decsp3
	lda     #<(_mensaje4)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje4)
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	lda     #$0A
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 252
	lda     #$32
	jsr     _delay
;
; fade_out_white(15);
;
	.dbg	line, "fullbg.c", 253
	lda     #$0F
	jsr     _fade_out_white
;
; palette[1] = 0x07;
;
	.dbg	line, "fullbg.c", 256
	lda     #$07
	sta     _palette+1
;
; palette[2] = 0x17;
;
	.dbg	line, "fullbg.c", 257
	lda     #$17
	sta     _palette+2
;
; palette[3] = 0x27;
;
	.dbg	line, "fullbg.c", 258
	lda     #$27
	sta     _palette+3
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 259
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; map_to(DISASTER);
;
	.dbg	line, "fullbg.c", 260
	lda     #$14
	jsr     _map_to
;
; load_nametable_a_during_vblank(disaster, 0x3C0);
;
	.dbg	line, "fullbg.c", 261
	lda     #<(_disaster)
	ldx     #>(_disaster)
	jsr     pushax
	ldx     #$03
	lda     #$C0
	jsr     _load_nametable_a_during_vblank
;
; ppu_wait_nmi();
;
	.dbg	line, "fullbg.c", 262
	jsr     _ppu_wait_nmi
;
; change_std_scanline(150);
;
	.dbg	line, "fullbg.c", 263
	lda     #$96
	jsr     _change_std_scanline
;
; fade_in_white(5);
;
	.dbg	line, "fullbg.c", 264
	lda     #$05
	jsr     _fade_in_white
;
; print(mensaje5, 7, 20);
;
	.dbg	line, "fullbg.c", 266
	jsr     decsp3
	lda     #<(_mensaje5)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje5)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 267
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 268
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje6, 7, 20);
;
	.dbg	line, "fullbg.c", 269
	jsr     decsp3
	lda     #<(_mensaje6)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje6)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 270
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 271
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje7, 3, 20);
;
	.dbg	line, "fullbg.c", 272
	jsr     decsp3
	lda     #<(_mensaje7)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje7)
	sta     (sp),y
	lda     #$03
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 273
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 274
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje8, 6, 20);
;
	.dbg	line, "fullbg.c", 275
	jsr     decsp3
	lda     #<(_mensaje8)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje8)
	sta     (sp),y
	lda     #$06
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 276
	lda     #$32
	jsr     _delay
;
; fade_out(3);
;
	.dbg	line, "fullbg.c", 277
	lda     #$03
	jsr     _fade_out
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 279
	jsr     _ppu_off
;
; map_to(DESERT);
;
	.dbg	line, "fullbg.c", 280
	lda     #$18
	jsr     _map_to
;
; vram_adr(NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 281
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_unrle(desert);
;
	.dbg	line, "fullbg.c", 282
	lda     #<(_desert)
	ldx     #>(_desert)
	jsr     _vram_unrle
;
; fix_text_color();
;
	.dbg	line, "fullbg.c", 283
	jsr     _fix_text_color
;
; ppu_on_all();
;
	.dbg	line, "fullbg.c", 284
	jsr     _ppu_on_all
;
; fade_in(4);
;
	.dbg	line, "fullbg.c", 285
	lda     #$04
	jsr     _fade_in
;
; print(mensaje9, 1, 20);
;
	.dbg	line, "fullbg.c", 287
	jsr     decsp3
	lda     #<(_mensaje9)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje9)
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 288
	lda     #$32
	jsr     _delay
;
; pal_fade_to(4,8);
;
	.dbg	line, "fullbg.c", 289
	lda     #$04
	jsr     pusha
	lda     #$08
	jsr     _pal_fade_to
;
; map_to(LIGHTINDESERT);
;
	.dbg	line, "fullbg.c", 291
	lda     #$1C
	jsr     _map_to
;
; load_nametable_a_during_vblank(lightInDesert, 0x3C0);
;
	.dbg	line, "fullbg.c", 292
	lda     #<(_lightInDesert)
	ldx     #>(_lightInDesert)
	jsr     pushax
	ldx     #$03
	lda     #$C0
	jsr     _load_nametable_a_during_vblank
;
; pal_fade_to(8,4);
;
	.dbg	line, "fullbg.c", 293
	lda     #$08
	jsr     pusha
	lda     #$04
	jsr     _pal_fade_to
;
; print(mensaje10, 6, 20);
;
	.dbg	line, "fullbg.c", 295
	jsr     decsp3
	lda     #<(_mensaje10)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje10)
	sta     (sp),y
	lda     #$06
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 296
	lda     #$32
	jsr     _delay
;
; fade_out(4);
;
	.dbg	line, "fullbg.c", 297
	lda     #$04
	jsr     _fade_out
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 299
	jsr     _ppu_off
;
; map_to(THE3HEROES);
;
	.dbg	line, "fullbg.c", 300
	lda     #$20
	jsr     _map_to
;
; vram_adr(NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 301
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_write(the3Heroes, sizeof(the3Heroes) - 64);
;
	.dbg	line, "fullbg.c", 302
	lda     #<(_the3Heroes)
	ldx     #>(_the3Heroes)
	jsr     pushax
	ldx     #$03
	lda     #$C0
	jsr     _vram_write
;
; vram_write(the3Heroes_attr, sizeof(the3Heroes_attr));
;
	.dbg	line, "fullbg.c", 303
	lda     #<(_the3Heroes_attr)
	ldx     #>(_the3Heroes_attr)
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     _vram_write
;
; fix_text_color();
;
	.dbg	line, "fullbg.c", 304
	jsr     _fix_text_color
;
; ppu_on_all();
;
	.dbg	line, "fullbg.c", 305
	jsr     _ppu_on_all
;
; fade_in(4);
;
	.dbg	line, "fullbg.c", 306
	lda     #$04
	jsr     _fade_in
;
; print(mensaje11, 0, 20);
;
	.dbg	line, "fullbg.c", 307
	jsr     decsp3
	lda     #<(_mensaje11)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje11)
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 308
	lda     #$32
	jsr     _delay
;
; custom_fade_in(1,6);
;
	.dbg	line, "fullbg.c", 309
	lda     #$01
	jsr     pusha
	lda     #$06
	jsr     _custom_fade_in
;
; print(mensaje12, 9, 20);
;
	.dbg	line, "fullbg.c", 310
	jsr     decsp3
	lda     #<(_mensaje12)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje12)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 311
	lda     #$32
	jsr     _delay
;
; custom_fade_in(2,6);
;
	.dbg	line, "fullbg.c", 312
	lda     #$02
	jsr     pusha
	lda     #$06
	jsr     _custom_fade_in
;
; print(mensaje13, 19, 20);
;
	.dbg	line, "fullbg.c", 313
	jsr     decsp3
	lda     #<(_mensaje13)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje13)
	sta     (sp),y
	lda     #$13
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 314
	lda     #$32
	jsr     _delay
;
; fade_out(4);
;
	.dbg	line, "fullbg.c", 315
	lda     #$04
	jsr     _fade_out
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 318
	jsr     _ppu_off
;
; for (i = 4; i<12; ++i){
;
	.dbg	line, "fullbg.c", 319
	lda     #$04
	sta     _i
L000A:	lda     _i
	cmp     #$0C
	bcs     L0006
;
; palette[i] = 0x0f;
;
	.dbg	line, "fullbg.c", 320
	ldy     _i
	lda     #$0F
	sta     _palette,y
;
; for (i = 4; i<12; ++i){
;
	.dbg	line, "fullbg.c", 319
	inc     _i
	jmp     L000A
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 322
L0006:	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; map_to(SEALANGELHEAVEN);
;
	.dbg	line, "fullbg.c", 323
	lda     #$24
	jsr     _map_to
;
; vram_adr(NAMETABLE_A);
;
	.dbg	line, "fullbg.c", 324
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_unrle(sealAngelHeaven);
;
	.dbg	line, "fullbg.c", 325
	lda     #<(_sealAngelHeaven)
	ldx     #>(_sealAngelHeaven)
	jsr     _vram_unrle
;
; fix_text_color();
;
	.dbg	line, "fullbg.c", 326
	jsr     _fix_text_color
;
; ppu_on_all();
;
	.dbg	line, "fullbg.c", 327
	jsr     _ppu_on_all
;
; fade_in(4);
;
	.dbg	line, "fullbg.c", 328
	lda     #$04
	jsr     _fade_in
;
; print(mensaje14, 0, 20);
;
	.dbg	line, "fullbg.c", 330
	jsr     decsp3
	lda     #<(_mensaje14)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje14)
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 331
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 332
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje15, 1, 20);
;
	.dbg	line, "fullbg.c", 333
	jsr     decsp3
	lda     #<(_mensaje15)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje15)
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(100);
;
	.dbg	line, "fullbg.c", 334
	lda     #$64
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 335
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje16, 6, 20);
;
	.dbg	line, "fullbg.c", 336
	jsr     decsp3
	lda     #<(_mensaje16)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje16)
	sta     (sp),y
	lda     #$06
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 337
	lda     #$32
	jsr     _delay
;
; clear_4_lines(20);
;
	.dbg	line, "fullbg.c", 338
	lda     #$14
	jsr     _clear_4_lines
;
; print(mensaje17, 6, 20);
;
	.dbg	line, "fullbg.c", 339
	jsr     decsp3
	lda     #<(_mensaje17)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(_mensaje17)
	sta     (sp),y
	lda     #$06
	ldy     #$00
	sta     (sp),y
	lda     #$14
	jsr     _print
;
; delay(50);
;
	.dbg	line, "fullbg.c", 340
	lda     #$32
	jsr     _delay
;
; fade_out(4);
;
	.dbg	line, "fullbg.c", 341
	lda     #$04
	jsr     _fade_out
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 342
	jsr     _ppu_off
;
; palette[1] = 0x07;
;
	.dbg	line, "fullbg.c", 343
	lda     #$07
	sta     _palette+1
;
; palette[2] = 0x17;
;
	.dbg	line, "fullbg.c", 344
	lda     #$17
	sta     _palette+2
;
; palette[3] = 0x27;
;
	.dbg	line, "fullbg.c", 345
	lda     #$27
	sta     _palette+3
;
; pal_bg(palette);
;
	.dbg	line, "fullbg.c", 346
	lda     #<(_palette)
	ldx     #>(_palette)
	jsr     _pal_bg
;
; pal_bright(0);
;
	.dbg	line, "fullbg.c", 347
	lda     #$00
	jsr     _pal_bright
;
; delay(100);
;
	.dbg	line, "fullbg.c", 348
	lda     #$64
	jsr     _delay
;
; ppu_off();
;
	.dbg	line, "fullbg.c", 349
	jsr     _ppu_off
;
; while (1){
;
	.dbg	line, "fullbg.c", 206
	jmp     L0002

	.dbg	line
.endproc

