; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses VRC6 expansion, you must set FAMISTUDIO_EXP_VRC6 = 1.
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_deltarunelegend=music_data_deltarunelegend
.endif

music_data_deltarunelegend:
	.byte 2
	.word @instruments
	.word @samples-5
; 00 : Part1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word 219,182
; 01 : Part2
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.word @song1ch7
	.word 219,182

.export music_data_deltarunelegend
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env9,@env11,@env0 ; 00 : Snare Noise
	.word @env7,@env4,@env11,@env0 ; 01 : Crash
	.word @env8,@env9,@env11,@env0 ; 02 : Lead Attack 2A03
	.word @env7,@env9,@env11,@env0 ; 03 : Blank 2A03
	.word @env7,@env9,@env11,@env0 ; 04 : Blank VRC6
	.word @env5,@env9,@env11,@env0 ; 05 : Lead Pluck 2A03
	.word @env7,@env12,@env11,@env0 ; 06 : Arp Lead Minor
	.word @env7,@env2,@env11,@env0 ; 07 : Arp Lead Major
	.word @env7,@env1,@env11,@env0 ; 08 : Arp Lead 2nd
	.word @env7,@env3,@env11,@env0 ; 09 : Arp Lead 5th
	.word @env7,@env10,@env11,@env0 ; 0a : Arp Lead 4th
	.word @env8,@env9,@env11,@env0 ; 0b : Lead Attack VRC6
	.word @env7,@env13,@env11,@env0 ; 0c : New instrument

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c0,$c2,$c2,$00,$00
@env2:
	.byte $c0,$c0,$c4,$c4,$00,$00
@env3:
	.byte $c0,$c0,$c7,$c7,$00,$00
@env4:
	.byte $be,$c0,$00,$01
@env5:
	.byte $00,$cf,$03,$ce,$03,$cd,$03,$cc,$03,$cb,$03,$ca,$00,$0b
@env6:
	.byte $00,$c7,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0a
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $00,$c1,$c5,$ca,$cf,$03,$ce,$03,$cd,$03,$cc,$03,$cb,$03,$ca,$00,$0e
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $c0,$c0,$c5,$c5,$00,$00
@env11:
	.byte $7f,$00,$00
@env12:
	.byte $c0,$c0,$c3,$c3,$00,$00
@env13:
	.byte $c0,$02,$c2,$c2,$c2,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e6,$0e,$40,$01 ; 00 C-3.dmc (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e6,$0f,$40,$01 ; 01 C-3.dmc (Pitch:15)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$f6,$0e,$40,$01 ; 02 D-3.dmc (Pitch:14)
	.byte $3a+.lobyte(FAMISTUDIO_DPCM_PTR),$f6,$0f,$40,$01 ; 03 D-3.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 04 E-2.dmc (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 05 F-2.dmc (Pitch:15)

@song0ch0:
	.byte $46, $03, $bf, $77, $4e, $00, $4f, $01, $84, $25, $9d, $24, $9d, $4f, $01, $25, $bd, $24, $85, $71, $87, $77, $20, $85
	.byte $71, $87, $77, $27, $8d, $71, $8f, $77, $4f, $01, $22, $ad, $20, $85, $1e, $85, $1d, $9d, $18, $8d, $20, $8d, $4f, $01
	.byte $1e, $9d, $1d, $8d, $22, $8d, $22, $8d, $21, $85, $1f, $85, $21, $9d, $71, $87, $00, $85
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8f, $79, $4f, $02, $84
@song0ref81:
	.byte $25, $85, $24, $85, $25, $85, $27, $85, $29, $8d, $49, .lobyte(@env0), .hibyte(@env0), $4a
@song0ref95:
	.byte $29, $85, $27, $85, $29, $85, $2a, $85, $2c, $9d, $73, $8f, $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
@song0ref114:
	.byte $2e, $85, $2c, $85, $2e, $85, $30, $85, $31, $8d, $30, $9d, $2c, $8d, $73, $8f, $79, $4f, $02
@song0ref133:
	.byte $2a, $8d, $29, $8d, $2a, $8d, $2e, $8d, $2c, $8d, $2a, $8d, $29, $8d, $25, $8d, $4f, $02
@song0ref151:
	.byte $27, $9d, $25, $8d, $29, $8d, $27, $9d, $29, $9d, $73, $87, $72, $87
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $86, $2e, $bd, $2c, $bd, $2a, $bd, $29, $85, $00, $85, $24, $85, $00, $85, $30, $9d, $27, $bd, $25, $9d, $20, $8d, $25
	.byte $8d, $23, $bd, $24, $9d, $29, $9d, $00, $8d
@song0ch2loop:
	.byte $81, $42
	.word @song0ch2loop
@song0ch3:
@song0ref208:
	.byte $00, $fd, $00, $fd, $00, $fd, $00, $fd, $00, $8d
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $ff, $ff, $8f
@song0ch4loop:
	.byte $81, $42
	.word @song0ch4loop
@song0ch5:
	.byte $00, $93, $72, $4e, $01, $4f, $07, $88
	.byte $41, $0a
	.word @song0ref81
	.byte $41, $09
	.word @song0ref95
	.byte $97, $95, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $07
	.byte $41, $0d
	.word @song0ref114
	.byte $97, $85, $4f, $07
	.byte $41, $0f
	.word @song0ref133
	.byte $87, $85, $4f, $07
	.byte $41, $09
	.word @song0ref151
	.byte $97, $85, $71, $87, $00
@song0ch5loop:
	.byte $00, $42
	.word @song0ch5loop
@song0ch6:
	.byte $41, $0a
	.word @song0ref208
@song0ch6loop:
	.byte $00, $42
	.word @song0ch6loop
@song0ch7:
	.byte $41, $0a
	.word @song0ref208
@song0ch7loop:
	.byte $00, $42
	.word @song0ch7loop
@song1ch0:
	.byte $71, $4f, $01, $84, $0a, $8d, $77, $11, $8d, $16, $9d, $71, $08, $8d, $77, $0f, $8d, $18, $9d, $71, $4f, $01, $8f, $77
	.byte $0d, $8d, $16, $8d, $12, $8d, $71, $8f, $77, $11, $8d, $14, $9d, $71, $4f, $01, $0f, $8d, $77, $14, $85, $16, $85, $14
	.byte $8d, $1b, $8d, $18, $9d, $14, $9d, $4f, $01, $19, $bd, $16, $95, $15, $81, $16, $81, $18
@song1ref67:
	.byte $9d, $4f, $02, $8a, $1d, $8d, $22, $85, $25, $85, $29, $8d, $27, $8d, $24, $8d, $22, $8d, $20, $9d, $4f, $02, $22, $8d
	.byte $22, $85, $24, $85, $25, $8d, $22, $8d, $24, $8d, $22, $8d, $24, $9d, $4f, $01, $1e, $8d, $22, $85, $25, $85, $2e, $8d
	.byte $2c, $8d, $27, $8d, $22, $8d, $24, $9d, $4f, $01, $84, $19, $bd, $16, $9d, $15
	.byte $41, $36
	.word @song1ref67
	.byte $9d, $4f, $01, $0a, $81, $71, $83, $77, $0a, $81, $71, $83, $77, $1d, $85, $1b, $85, $1d, $85, $1e, $85, $20, $8d, $20
	.byte $89, $1e, $81, $20, $89, $22, $81, $24, $8d, $25, $85, $27, $85, $4f, $01, $29, $95, $2c, $85, $29, $95, $27, $85, $24
	.byte $bd, $4f, $02, $22, $85, $20, $85, $22, $85, $25, $85, $24, $85, $22, $85, $20, $85, $22, $85, $24, $8d, $20, $85, $1e
	.byte $85, $20, $8d, $1d, $85, $20, $85, $4f, $02, $22, $95, $22, $85, $20, $8d, $1e, $8d, $1d, $9d, $75, $21, $9d, $4e, $01
	.byte $00, $8b, $72, $4f, $00, $86
@song1ref236:
	.byte $30, $81, $31, $81, $30, $81, $2e, $81, $29, $81, $71, $83, $72, $25, $81, $71, $83, $72, $29, $81, $71, $83, $00, $85
	.byte $72
	.byte $41, $08
	.word @song1ref236
	.byte $33, $8f, $85, $71, $87, $72
	.byte $41, $08
	.word @song1ref236
	.byte $30, $8d, $31, $81, $71, $83, $72, $2c, $81, $71, $83, $72
@song1ref285:
	.byte $2c, $81, $2a, $81, $29, $81, $2a, $81, $29, $8f, $85, $71, $87, $72
@song1ref299:
	.byte $29, $81, $2a, $81, $29, $81, $27, $81, $23, $85, $1e, $85, $2a, $85, $29, $89, $27, $81, $25, $81, $27, $81, $29, $8d
	.byte $25, $85, $28, $85, $24, $85, $22, $85, $1c, $8d, $28, $85, $29, $c5, $71, $81
@song1ch0loop:
	.byte $00, $42
	.word @song1ch0loop
@song1ch1:
	.byte $79, $4f, $02, $84
@song1ref348:
	.byte $16, $8d, $19, $85, $1d, $85, $25, $8d, $24, $8d, $20, $8d, $1b, $8d, $1d, $9d, $4f, $02, $1d, $8d, $1e, $85, $20, $85
	.byte $1e, $8d, $1d, $8d, $1b, $8d, $19, $8d, $1d, $9d, $4f, $02
	.byte $41, $20
	.word @song1ref348
@song1ref387:
	.byte $4f, $02, $8a
@song1ref390:
	.byte $22, $8d, $25, $85, $29, $85, $31, $8d, $30, $8d, $2c, $8d, $27, $8d, $29, $9d, $4f, $02, $29, $8d, $2a, $85, $2c, $85
	.byte $2a, $8d, $29, $8d, $27, $8d, $25, $8d, $29, $9d, $4f, $01
	.byte $41, $10
	.word @song1ref390
@song1ref429:
	.byte $4f, $02, $84
@song1ref432:
	.byte $35, $8d, $36, $85, $38, $85, $36, $8d, $35, $8d, $33, $8d, $31, $8d, $35, $9d
	.byte $41, $20
	.word @song1ref387
	.byte $4f, $01
	.byte $41, $10
	.word @song1ref390
	.byte $41, $10
	.word @song1ref429
	.byte $4f, $01, $16, $81, $73, $83, $79, $16, $81, $73, $83, $79, $25, $85, $24, $85, $25, $85, $27, $85, $29, $8d, $29, $89
	.byte $27, $81, $29, $89, $2a, $81, $2c, $8d, $2e, $85, $30, $85, $4f, $01, $31, $95, $33, $85, $31, $95, $30, $85, $2c, $bd
	.byte $4f, $02, $2a, $85, $29, $85, $2a, $85, $2e, $85, $2c, $85, $2a, $85, $29, $85, $2a, $85, $2c, $8d, $29, $85, $27, $85
	.byte $29, $8d, $25, $85, $29, $85, $4f, $02, $2a, $95, $29, $85, $27, $8d, $25, $8d, $24, $9d, $77, $29, $9d, $00, $85, $79
	.byte $4f, $00
	.byte $41, $0a
	.word @song1ref236
	.byte $72, $83, $79, $25, $81, $72, $83, $79, $29, $81, $72, $83, $71, $87, $79
	.byte $41, $08
	.word @song1ref236
	.byte $33, $95, $72, $83, $71, $83, $79
	.byte $41, $08
	.word @song1ref236
	.byte $30, $8d, $31, $81, $72, $83, $79, $2c, $81, $72, $83, $79
	.byte $41, $09
	.word @song1ref285
	.byte $95, $72, $83, $71, $83, $79
	.byte $41, $26
	.word @song1ref299
	.byte $72, $83, $71, $83
@song1ch1loop:
	.byte $00, $42
	.word @song1ch1loop
@song1ch2:
	.byte $86, $16, $bd, $14, $bd, $12, $bd, $11, $bd, $1b, $bd, $19, $bd
@song1ref634:
	.byte $23, $bd, $24, $8d, $18, $8d, $1d, $8d, $21, $8d
@song1ref644:
	.byte $16, $85, $1d, $85, $22, $85, $1d, $85
	.byte $41, $08
	.word @song1ref644
@song1ref655:
	.byte $14, $85, $1b, $85, $24, $85, $1b, $85
	.byte $41, $08
	.word @song1ref655
@song1ref666:
	.byte $12, $85, $19, $85, $22, $85, $19, $85
	.byte $41, $08
	.word @song1ref666
@song1ref677:
	.byte $11, $85, $18, $85, $1b, $85, $18, $85
	.byte $41, $08
	.word @song1ref677
@song1ref688:
	.byte $0f, $85, $16, $85, $1b, $85, $16, $85
	.byte $41, $08
	.word @song1ref688
@song1ref699:
	.byte $0d, $85, $14, $85, $18, $85, $19, $85, $1b, $85, $1d, $85, $20, $85, $24, $85
	.byte $41, $12
	.word @song1ref634
	.byte $41, $08
	.word @song1ref644
	.byte $41, $08
	.word @song1ref655
	.byte $41, $08
	.word @song1ref655
	.byte $41, $08
	.word @song1ref666
	.byte $41, $08
	.word @song1ref666
	.byte $41, $08
	.word @song1ref677
	.byte $41, $08
	.word @song1ref677
	.byte $41, $08
	.word @song1ref688
	.byte $41, $08
	.word @song1ref688
	.byte $41, $10
	.word @song1ref699
	.byte $41, $0a
	.word @song1ref634
	.byte $0a, $81, $00, $81, $0a, $b5, $08, $bd, $12, $bd, $1d, $8d, $24, $8d, $2c, $8d, $27, $8d, $84, $1b, $bd, $19, $bd, $86
	.byte $17, $bd, $18, $9d, $21, $9d, $84
@song1ref782:
	.byte $22
@song1ref783:
	.byte $85, $29, $81, $00, $81, $29, $81, $00, $81
	.byte $41, $0a
	.word @song1ref782
	.byte $20
	.byte $41, $09
	.word @song1ref783
	.byte $20
	.byte $41, $09
	.word @song1ref783
	.byte $1e
	.byte $41, $09
	.word @song1ref783
	.byte $1e, $85
@song1ref809:
	.byte $25, $81, $00, $81, $29, $81, $00, $81, $86, $25, $85, $2c, $81, $00, $81, $2c, $81, $00, $81, $2c, $81, $98, $2a, $81
	.byte $86
	.byte $41, $09
	.word @song1ref299
@song1ref837:
	.byte $83, $00, $27, $81, $00, $81, $2a, $81, $00, $81, $23
	.byte $41, $0a
	.word @song1ref837
	.byte $22, $83, $00
	.byte $41, $08
	.word @song1ref809
	.byte $22, $83, $00
	.byte $41, $08
	.word @song1ref809
@song1ref863:
	.byte $24, $83, $00, $2b, $81, $00, $81, $2b, $81, $00, $81
	.byte $41, $0b
	.word @song1ref863
	.byte $29, $81, $00, $85, $30, $81, $00, $85, $30, $81, $00, $85, $29, $a1, $00, $85
@song1ch2loop:
	.byte $00, $42
	.word @song1ch2loop
@song1ch3:
	.byte $00, $fd, $00, $fd, $00, $fd, $df, $80
@song1ref906:
	.byte $1a, $85, $1a, $85, $74, $1a, $78, $1a, $7c, $1a, $81, $7f, $1a, $81, $1a
@song1ref921:
	.byte $81
@song1ref922:
	.byte $79, $82, $1f, $78, $81, $77, $81, $76, $81, $75, $83, $74, $83, $73, $83, $72, $83, $71, $83, $78, $80, $1a, $81, $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
@song1ref973:
	.byte $85, $1a, $85, $1a, $81, $78, $1a, $81, $7f, $1a, $85, $1a, $81, $78, $1a, $81, $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $08
	.word @song1ref906
	.byte $71, $86, $1e, $72, $81, $73, $81, $74
	.byte $41, $0c
	.word @song1ref921
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85
	.byte $41, $0b
	.word @song1ref922
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $41, $0d
	.word @song1ref973
	.byte $7f
	.byte $41, $09
	.word @song1ref906
	.byte $85, $00, $fd, $df, $df, $df, $ff
@song1ch3loop:
	.byte $00, $42
	.word @song1ch3loop
@song1ch4:
	.byte $46, $03, $ff, $ff, $ff
@song1ref1144:
	.byte $ff, $03, $ad, $03, $8d, $01, $ad, $01, $8d, $06, $ad, $06, $8d, $05, $bd, $04, $ad, $04, $8d, $02, $9d, $02, $9d
	.byte $41, $17
	.word @song1ref1144
	.byte $ff, $03, $85, $03, $a5, $03, $8d, $01, $85, $01, $a5, $01, $8d, $06, $85, $06, $a5, $06, $8d, $05, $85, $05, $a5, $05
	.byte $8d, $ff, $ff, $46, $04, $df, $46, $04, $df, $46, $04, $df, $46, $04, $ff
@song1ch4loop:
	.byte $81, $42
	.word @song1ch4loop
@song1ch5:
@song1ref1214:
	.byte $00, $fd, $00, $fd, $00, $fd, $00, $fd
@song1ref1222:
	.byte $71, $4e, $01, $4f, $07, $8c, $22
@song1ref1229:
	.byte $85, $72, $87, $73, $87, $74, $87, $75, $87, $74, $87, $73, $87, $72, $87, $71, $8e, $20, $85, $72, $87, $73, $90, $20
	.byte $85, $74, $87, $75, $8e, $20, $85, $74, $87, $73, $87, $72, $87, $71, $4e, $01, $4f, $07, $1e
	.byte $41, $08
	.word @song1ref1229
@song1ref1275:
	.byte $71, $92, $1d, $85, $72, $87, $73, $94, $1d, $85, $74, $87, $75, $8c, $1d, $85, $74, $87, $73, $87, $72, $87, $00, $fd
	.byte $85, $4e, $01, $4f, $07, $88
	.byte $41, $0f
	.word @song1ref432
	.byte $97
	.byte $41, $15
	.word @song1ref1222
	.byte $41, $08
	.word @song1ref1229
	.byte $41, $0e
	.word @song1ref1275
	.byte $4e, $01, $4f, $07, $88
	.byte $41, $0f
	.word @song1ref432
	.byte $97, $75, $4f, $03, $96, $40, $0a, $81, $71, $83, $75, $40, $0a, $81, $71, $83, $75, $22, $85, $20, $85, $22, $85, $24
	.byte $85, $25, $8d, $25, $9d, $24, $9d, $4f, $03, $0a, $95, $0c, $85, $0d, $8d, $16, $8d, $14, $9d, $1b, $9d, $71, $4f, $07
	.byte $88, $0f
	.byte $41, $08
	.word @song1ref1229
	.byte $71, $11
	.byte $41, $08
	.word @song1ref1229
@song1ref1384:
	.byte $00, $fd
@song1ref1386:
	.byte $00, $dd, $00, $dd, $00, $dd, $00, $fd
@song1ch5loop:
	.byte $00, $42
	.word @song1ch5loop
@song1ch6:
	.byte $41, $08
	.word @song1ref1214
	.byte $4e, $01, $4f, $03, $8f, $76, $96
@song1ref1409:
	.byte $0d, $8d, $16, $9d, $72, $8f, $76, $0f, $8d, $18, $9d, $4e, $01, $4f, $03, $00, $8d, $0d, $8d, $16, $8d, $11, $8d, $72
	.byte $8f, $76, $11, $8d, $14, $9d, $4f, $03, $8f, $75, $1e, $9d, $20, $8d, $1d, $9d, $00, $8d, $24, $8d, $00, $fd, $4e, $01
	.byte $4f, $03, $8f, $76
	.byte $41, $23
	.word @song1ref1409
	.byte $00, $fd, $71, $4f, $07, $88, $1e, $85, $72, $87, $73, $87, $74, $20, $85, $75, $22, $85, $74, $87, $73, $27, $85, $72
	.byte $87, $71, $24
	.byte $41, $08
	.word @song1ref1229
	.byte $71, $4f, $03, $19
	.byte $41, $08
	.word @song1ref1229
	.byte $71, $18, $85, $72, $87, $73, $87, $74, $87, $75, $14, $85, $74, $87, $73, $87, $72, $87, $75, $4f, $03, $1b, $bd, $1b
	.byte $9d, $73, $18, $9d
	.byte $41, $08
	.word @song1ref1386
@song1ch6loop:
	.byte $00, $42
	.word @song1ch6loop
@song1ch7:
	.byte $41, $08
	.word @song1ref1214
	.byte $73, $4e, $01, $88
@song1ref1544:
	.byte $40, $0a
@song1ref1546:
	.byte $85, $74, $87, $75, $87, $76, $87, $77, $87, $76, $87, $75, $87, $74, $87, $73, $40, $08
	.byte $41, $08
	.word @song1ref1546
	.byte $73, $4e, $01, $40, $06
	.byte $41, $08
	.word @song1ref1546
	.byte $73, $40, $05
	.byte $41, $08
	.word @song1ref1546
@song1ref1581:
	.byte $73, $0f, $85, $74, $87, $75, $87, $76, $87, $77, $12, $85, $76, $87, $75, $14, $85, $74, $87, $73, $11, $85, $74, $87
	.byte $75, $87, $76, $87, $77, $18, $85, $76, $87, $75, $87, $74, $87, $00, $fd, $73, $4e, $01
	.byte $41, $0a
	.word @song1ref1544
	.byte $41, $08
	.word @song1ref1546
	.byte $73, $4e, $01, $40, $06
	.byte $41, $08
	.word @song1ref1546
	.byte $73, $40, $05
	.byte $41, $08
	.word @song1ref1546
	.byte $41, $17
	.word @song1ref1581
	.byte $87
@song1ref1647:
	.byte $73, $29, $81, $71, $83, $73, $27, $81, $71, $29, $81, $73, $29, $81, $71, $27, $81, $29, $81, $70, $83
	.byte $41, $0e
	.word @song1ref1647
	.byte $41, $0e
	.word @song1ref1647
	.byte $73, $29, $81, $71, $83, $73, $27, $81, $71, $29, $81, $73, $2c, $81, $71, $27, $81, $2c, $81, $70, $83, $73, $2e, $81
	.byte $71, $83, $73, $29, $81, $71, $2e, $81, $73, $2e, $81, $71, $29, $81, $2e, $81, $70, $83, $73, $31, $81, $71, $2e, $81
	.byte $73, $2e, $81, $71, $31, $81, $73, $29, $81, $71, $2e, $81, $73, $2c, $81, $71, $29, $81, $73, $27, $81, $71, $2c, $81
	.byte $73, $29, $81, $71, $27, $81, $73, $2c, $81, $71, $29, $81, $73, $33, $81, $71, $2c, $81, $73, $30, $81, $71, $33, $81
	.byte $73, $2c, $81, $71, $30, $81, $73, $27, $81, $71, $2c, $81, $73, $03, $85, $74, $87, $75, $87, $76, $87, $77, $06, $85
	.byte $76, $87, $75, $08, $85, $74, $87, $73, $01, $85, $74, $87, $75, $87, $76, $87, $77, $08, $85, $76, $87, $75, $87, $74
	.byte $87
	.byte $41, $0a
	.word @song1ref1384
@song1ch7loop:
	.byte $00, $42
	.word @song1ch7loop
